name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com

jobs:
  test-action: # make sure build/ci work properly
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: vmware-labs/vmware-image-builder-action@pipeline-duration-customization
        with:
          path: '/'
          config: '.vib'
          pipeline: 'vib-pipeline.json'
          retry-count: 5
          backoff-intervals: '[100, 500, 1000, 2000, 5000]'
  summary: 
    name: Summary
    runs-on: ubuntu-latest
    
    steps:
    - name: Simple job summary
      run: echo '### Hello world :rocket:' >> $GITHUB_STEP_SUMMARY
    
    - name: Generate a table of results
      run: |
        echo "Test Result :test_tube: | Passed :green_circle: | Failed :x: | Skipped | Time Duration :alarm_clock: |" >> $GITHUB_STEP_SUMMARY
        echo "| --------- | ------ | ------ | ------- | ------------- |" >> $GITHUB_STEP_SUMMARY
        echo "| :green_circle: Passed | 122 | 0 | 3 | 12m 3s |" >> $GITHUB_STEP_SUMMARY
        echo "| :x: Failed | 121 | 2 | 3 | 10m 3s |" >> $GITHUB_STEP_SUMMARY
        echo "| :green_circle: Passed | 4 | 12 | 3 | 9m 4s |" >> $GITHUB_STEP_SUMMARY
