name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com

jobs:
  test-action: # make sure build/ci work properly
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: vmware-labs/vmware-image-builder-action@test-branch
        with:
          path: '/'
          config: '.vib'
          pipeline: 'vib-pipeline.json'
          retry-count: 5
          backoff-intervals: '[100, 500, 1000, 2000, 5000]'
          max-pipeline-duration: '24000'
